sol-eng/wbi

cmd/setup.go, internal/system/command.go, internal/workbench/download.go, internal/workbench/install.go, internal/workbench/prompt.go, internal/workbench/verify.go
This is a first attempt at building out the feature described in: https://github.com/dpastoor/wbi/issues/7
It is structured so first it tries to detect Workbench. If Workbench is installed it skips the install step. If Workbench is not installed, it offers to install.
It grabs metadata from here: https://www.rstudio.com/wp-content/downloads.json and parses out the correct installer URL/name based on the detected OS. Then it downloads the correct installer into a tmp directory, runs any prerequisites (upgrades apt and installs gdebi-core if Ubuntu) and then installs Workbench.
I read that `http.Client{}` only needs to be defined once per app but was having trouble figuring out where in the app it goes so it can be used by various internal packages. Right now I created it in two spots so …
=> First attempt at adding Workbench installer capabilities

cmd/setup.go, internal/languages/R.go, internal/languages/installR.go, internal/system/command.go
This is a first attempt at building out the feature described in: https://github.com/dpastoor/wbi/issues/8
It is structured so first it detects versions of R.
If R is installed but not in a /opt location then it gives the user the option of installing 1 or more versions.
If R is not installed at all then it gives the user the option of installing 1 or more versions (if not then it ends the program as R is required)
The prompt allows a user to select from a list of versions (right now the same list as on our docs site, although its hardcoded and should be done dynamically at some point). Then it loops through each version, downloads the correct installer into a tmp directory, runs any prerequisites (upgrades apt and installs gdebi-core if Ubuntu, optional repo in RHEL) and then installs …
=> Add R installation capability

cmd/setup.go, internal/authentication/prompt.go, internal/config/config.go, internal/config/convert.go, internal/config/print.go
This is a first step at the issue here: https://github.com/dpastoor/wbi/issues/4
Essentially these methods convert the internal config structs and prints the various config information out to the console so users know what to add to the various config files.
There is a lot more we can do here in terms of writing/reading config files automatically. There are some packages that have a lot of features like: https://github.com/spf13/viper we could use to do more fancy parsing.
=> Add config conversion

cmd/setup.go, internal/license/detect.go, internal/license/prompt.go, internal/system/command.go
Closes https://github.com/dpastoor/wbi/issues/29
The license activation flow now is as follows...
1. Detect if Workbench has an activate license already (if so then skip the rest)
2. If nothing is active, ask the user if they want to activate with a license key
3. If a user says yes, then it prompts for a license key which is then activated
=> Expand license activation flow to detect if active and allow skipping

internal/languages/python.go
Closes https://github.com/dpastoor/wbi/issues/30
Fix a bug with using the wrong function (RSelectVersionsPrompt being used in a Python section)
=> Change to the correct Python function call

internal/languages/installPython.go
Closes https://github.com/dpastoor/wbi/issues/19
Now after installing a version of Python into /opt/python, Workbench automatically upgrades pip, setuptools and wheel.
=> Add to python setup

cmd/setup.go, internal/config/config.go, internal/config/print.go, internal/connect/prompt.go, internal/connect/verify.go
Closes https://github.com/dpastoor/wbi/issues/22
This PR adds the following prompts:
1. Ask users if they want to enter a default Connect URL
2. If yes, then asks users to enter a URL
3. The URL is cleaned and validated
The validation was a bit tricky here but in the end used the health check __ping__ endpoint to ensure the address is correct. The verify code cleans up the URL first (removes a trailing slash, if not http/https adds it) and then verifies a good success code.
Video below
https://user-images.githubusercontent.com/180123/219785733-efddb0f2-7ed0-4ff2-a277-72fdb18d0e5f.mov
=> Add connect url prompt

cmd/setup.go, internal/config/config.go, internal/config/print.go, internal/packagemanager/construct.go, internal/packagemanager/prompt.go, internal/packagemanager/verify.go
Closes https://github.com/dpastoor/wbi/issues/20
This PR add support for users adding a default CRAN repo for Workbench pointed to either their own Posit Package Manager or Posit Public Package Manager.
1. Ask the user if they would like to make PPM their default CRAN repo
2. If yes, ask for the base url
3. Ask for the repo name
4. First the based URL is checked for connectivity/correctness, then the repo name is searched via the PPM API to verify it exists
5. Once the checks have past wbi outputs the correct config file in /etc/rstudio/repos.conf
6. If the user says no to step 1 then it asks them if they would like to setup PPPM
7. If they say yes to PPPM then it validates connectivity to the server
8. Once the checks have past wbi outputs the correct config file in …
=> Add package manager url prompts

cmd/setup.go, internal/config/config.go, internal/config/detect.go, internal/config/print.go, internal/config/prompt.go, internal/config/write.go, internal/languages/R.go, internal/workbench/restart.go, internal/workbench/verify.go
Closes https://github.com/dpastoor/wbi/issues/45
This PR provides the functionality to detect when there are config changes and offer the option to a user to have the changes written directly to the files and have rstudio-server and rstudio-launcher restarted.
Currently this only writes new lines to existing files (if no file exists it will create it). There is NO detection of existing duplicate config settings, this is assumed to be used a fresh server.
Video below:
https://user-images.githubusercontent.com/180123/220641571-8f7f1d9a-a75a-48b8-adbb-6a92b9900065.mov
=> Add the ability to write automatically to config files

cmd/install.go, go.mod, go.sum, internal/languages/R.go, internal/languages/python.go, internal/languages/versions.go
This resolves the following issues:
https://github.com/sol-eng/wbi/issues/24
https://github.com/sol-eng/wbi/issues/25
Adds the ability to block specific versions of python for specific osTypes because our builds aren't consistent in any helpful way.
https://connect.rstudioservices.com/python-builds-status/
Also allows you to block Major.Minor versions that are newer than a specific version, because we aren't building for CentOS7 anymore.
=> Pull the correct versions of R and Python Dynamically

internal/connect/prompt.go, internal/languages/R.go, internal/languages/python.go
Works at addressing https://github.com/sol-eng/wbi/issues/66
When selecting R and Python versions, if no versions are selected, it will ask for another selection rather than erroring out.
=> Add retries for R and Python

internal/packagemanager/prompt.go, internal/packagemanager/verify.go, internal/workbench/config.go
This PR closes https://github.com/sol-eng/wbi/issues/118 and works at but does not entirely fix: https://github.com/sol-eng/wbi/issues/66.
Essentially a loop is created for each prompt and verify section, only broken out when a verify is successful or a user types "skip". There is some code needed to make sure that when a user skips, it skips the rest of the package manager prompts so if you skip at the URL stage, you will skip the repo entry too and go to the next set of Connect prompts.
=> Adjust how errors are handled in Package Manager prompts

internal/languages/R.go, internal/languages/python.go, internal/languages/versions.go
Closes https://github.com/sol-eng/wbi/issues/111
This PR sorts the /opt/R and /opt/python paths in the scanning function for each R and Python. Since the scanning function is used throughout `wbi` from listing initial R and Python paths found to providing options for the choice of Jupyter and extra kernels, this change propagates throughout `wbi` and sorts neatly.
=> Add version sorting of /opt to both R and Python during scanning

internal/jupyter/install.go, internal/languages/python.go
This PR fixes an issue with installing older versions of Python which come with pip versions before 22.1 which currently break due to this option not existing `--root-user-action=ignore`. Instead this PR used the env variable `PIP_ROOT_USER_ACTION=ignore` which will take effect in 22.1 and later but not harm anything before that in older versions. I don't know of any way to actually ignore that error in pip pre 22.1.
=> Switch to an env variable to ignore root warning

README.md, cmd/setup.go, internal/operatingsystem/detect.go, internal/operatingsystem/prompt.go, internal/operatingsystem/user.go, internal/workbench/verify.go
Closes https://github.com/sol-eng/wbi/issues/126
This PR adds a step "user" to `wbi setup` command, which prompts for a non-root username and then validates the user is not root and has a home directory. Then in the "verify" step it uses the previously found username (or if invoked directly prompts then for a username) and includes it in the verify-installation command for a true verification.
Screenshot below from a fresh RHEL 9 install:
=> Add user step to setup and add prompt user with lookup and validation

cmd/setup.go
Closes https://github.com/sol-eng/wbi/issues/160
Wrapped all messages at the top level in the `setup` command to include a message on what step flag to use to resume. I opted to include a message for every error so the user can at least get back to the step before the error occurred (sometimes it could be a command or two up since the steps don't map one to one). I think this is a good flow but open to other suggestions @samcofer
=> Wrap all error messages with a helpful message on the return step to use

README.md, cmd/install.go, cmd/install_test.go, cmd/setup.go, internal/operatingsystem/prompt.go, internal/quarto/check.go, internal/quarto/install.go, internal/quarto/prompt.go
This PR closes https://github.com/sol-eng/wbi/issues/159 and https://github.com/sol-eng/wbi/issues/143
It adds a quarto installation and symlink support to the `wbi install` command as well as a series of quarto install and symlink prompts in the `wbi setup` flow. If the bundled Workbench quarto is detected it lets the user know and askes if they want to install any additional versions of Quarto. If the answer is no, then wbi will still automatically symlink quarto so it works across editors. If the answer is yes, it will let them choose their versions.
Note, currently the Quarto versions are hard coded, TODO to add automatic retrieval from GitHub releases.
=> Add quarto support

cmd/setup.go
This PR adds some language to the final message directing people to access Workbench on the default :8787 if using HTTP or their URL without a port but using HTTPS. This way it is easier for users to quickly go login on their new server.
=> Add information to the final message regarding how to access Workbench

cmd/setup.go, internal/connect/prompt.go, internal/packagemanager/prompt.go
Closes https://github.com/sol-eng/wbi/issues/164
This PR gives the user of setup the option of selecting Posit Package Manager, Posit Public Package Manager or Skipping entirely to make the Posit Public Package Manager option more obvious. Many customers use Posit Public Package Manager so making it obvious and an easy default will help installs go smoother.
=> Change the flow of package manager and update wording

internal/workbench/config.go
Closes https://github.com/sol-eng/wbi/issues/151 by removing the commented out default line so there is only one active jupyter-exe line in the config
=> Ensure default commented out jupyter line is removed

internal/workbench/install.go
The downloads.json file here: https://www.rstudio.com/wp-content/downloads.json
No longer references bionic, since it's unsupported as of MH for Workbench. The top level entry is focal. We probably need to drop support for Bionic, but I haven't refactored all of that. Just taken care of the basic lookup failures.
=> Change in response to change in downloads.json from bionic to focal

internal/operatingsystem/install.go
Closes https://github.com/sol-eng/wbi/issues/183
Adding in the step to enable the extra repo for RHEL 7 only as `libev-devel` is no longer in EPEL.
=> Add enabling extra repo for RHEL 7

README.md, cmd/setup.go, internal/config/config.go, internal/install/install.go, internal/languages/install.go, internal/logging/command.go, internal/operatingsystem/detect.go, internal/operatingsystem/install.go, internal/packagemanager/construct.go, internal/prodrivers/install.go, internal/ssl/trust.go, internal/workbench/install.go
Ubuntu 18 is no longer supported by the product. This PR removes all mentions of Ubuntu 18 and closes https://github.com/sol-eng/wbi/issues/178
=> Remove Ubuntu18 support

.gitignore, cmd/install_test.go, go.mod, internal/quarto/install.go, internal/quarto/prompt.go
Pull quarto versions dynamically from github API. The results from the API are paginated with 100 results per page and there are a lot of releases.... 1300ish right now. Additionally, I exclude pre-lease versions to make sure we're only installing properly released versions.
=> Dynamic quarto

.github/workflows/build-test.yml
Add CGO_ENABLED to the compilation environment to ensure that importing C doesn't cause the build to fail. Since we don't actually use c libraries, we can maintain cross compatibly according to my testing.
=> Update github workflow to allow for the building of CGO_ENABLED binaries
