sol-eng/wbi

- internal/jupyter/install.go
- internal/license/activate.go
- internal/license/prompt.go
- internal/system/command.go
A few changes, which is an attempt to close https://github.com/dpastoor/wbi/issues/3
1. Created a generic function `RunCommand()` in the `system` package so it can be called by other packages in the application.
2. Structured `RunCommand()` so it prints the stdout and stderr incrementally with error handling
3. Hooked up the two Jupyter install functions and the license activation function to the new `RunCommand()` command
Video below!
https://user-images.githubusercontent.com/180123/218337146-31c4ce83-fbda-4469-a861-10e32b51f577.mp4
> Refactor how commands are handled

- cmd/setup.go
- internal/languages/R.go
- internal/languages/installPython.go
- internal/languages/python.go
Closes https://github.com/dpastoor/wbi/issues/9
Installs Python in a similar manner to the R installer. Currently also hard coding in Python versions, will switch to dynamically querying https://cdn.posit.co/python/versions.json in a future PR.
Video below:
https://user-images.githubusercontent.com/180123/218880709-e97b22a6-1a5c-43bd-aa31-ac1cbb51f6af.mp4
> Add python installer

- cmd/setup.go
Implements and closes the issue documented here: https://github.com/dpastoor/wbi/issues/27
The first few steps of WBI match the order of the docs here: https://docs.posit.co/rsw/installation/
> Restructure the flow of wbi to match docs

- cmd/setup.go
- internal/install/install.go
- internal/jupyter/install.go
- internal/license/activate.go
- internal/license/detect.go
- internal/os/install.go
- internal/os/root.go
- internal/prodrivers/install.go
- internal/workbench/install.go
- internal/workbench/restart.go
- internal/workbench/verify.go
Closes https://github.com/dpastoor/wbi/issues/42
This PR removes all sudo usage and adds a check right at the start of `wbi setup` to ensure users are running wbi as root.
> Remove sudo force running root

- internal/config/write.go
Closes https://github.com/dpastoor/wbi/issues/48
> Fix bug with incorrect error blocking write to config

- cmd/setup.go
Closes https://github.com/dpastoor/wbi/issues/51
> Change the saved jupyter path to end in jupyter not python

- README.md
Total time for the install was just a hair over 5 min. Thought it made for a great action gif, loving the tool! 
Also added a note about the importance of ownership for the file with chmod 777 preventing a brief error I had experienced due to how I uploaded the file originally. Potentially useful as a note for other Windows admins using MobaXTerm.
> Adding gif to show the tool in action!

- internal/install/download.go
- internal/languages/install.go
- internal/os/install.go
Closes https://github.com/sol-eng/wbi/issues/62
> Fix bugs related to RHEL

- internal/languages/R.go
- internal/languages/python.go
This PR closes https://github.com/sol-eng/wbi/issues/110
> Fix formatting issues

- internal/operatingsystem/prompt.go
Added some auth steps, clarified the repo name is needed for PM and added a step so the admin knows they will need to designate a default R and Python repo (symlink, path add and jupyter install)
@samcofer this is clean 2nd attempt at this PR, please review :) At some point soon we should test the auth pieces with a real IdP.
> Update intro message

- internal/install/install.go
- internal/jupyter/install.go
- internal/languages/R.go
- internal/languages/python.go
- internal/license/activate.go
- internal/license/detect.go
- internal/operatingsystem/firewall.go
- internal/operatingsystem/install.go
- internal/operatingsystem/linuxsecurity.go
- internal/operatingsystem/root.go
- internal/prodrivers/install.go
- internal/prodrivers/verify.go
- internal/system/command.go
- internal/workbench/install.go
- internal/workbench/restart.go
- internal/workbench/status.go
- internal/workbench/verify.go
Closes https://github.com/sol-eng/wbi/issues/115
> Change run commands to take a display and delay value and set them in wbi

- internal/connect/prompt.go
Works towards fixing https://github.com/sol-eng/wbi/issues/66 by providing the user a chance to retry entering an incorrect Connect URL with the option to skip if they get stuck.
> Add retry prompts with a skip option to Connect prompt

- internal/jupyter/install.go
- internal/jupyter/prompt.go
Closes https://github.com/sol-eng/wbi/issues/119
The prompt will exclude the Python version where Jupyter is already installed and set all /opt Python locations as selected by default.
> Add prompts and functions to register additional Python Jupyter kernels

- cmd/activate.go
- cmd/config.go
- cmd/install.go
- cmd/scan.go
- cmd/setup.go
- cmd/verify.go
Closes https://github.com/sol-eng/wbi/issues/134
> Silence usage and second error when erroring out

- cmd/setup.go
- cmd/verify.go
- internal/ssl/prompt.go
- internal/ssl/verify.go
> Adding SSL-verification and writing of ssl configuration once verified

- internal/jupyter/install.go
- internal/languages/python.go
Closes https://github.com/sol-eng/wbi/issues/139
Added the following commands to all pip install calls in `wbi`:
```
--no-warn-script-location --disable-pip-version-check --root-user-action=ignore
```
> Add root pip ignore and other ignore pip commands

- cmd/setup.go
- internal/ssl/prompt.go
- internal/ssl/trust.go
- internal/ssl/verify.go
closes https://github.com/sol-eng/wbi/issues/146
> Allow Administrators to optionally trust the CA in the provided SSL Certificate chain file

- internal/ssl/trust.go
- internal/system/path.go
- internal/system/write.go
- internal/workbench/config.go
Closes https://github.com/sol-eng/wbi/issues/155
> Add the print and log directly to WriteStrings

- LICENSE
- README.md
Clean up README to include usage of individual commands, information about logs, information about command logs and supportability messages.
Easiest way to see the changes is to look here on GitHub to see the README rendered: [https://github.com/sol-eng/wbi/tree/reformat-readme](https://github.com/sol-eng/wbi/tree/reformat-readme)
> Reformat README

- internal/quarto/install.go
This PR fixes and issue with the quarto installation commands
> Fix quarto command log

- internal/jupyter/install.go
Following the new guidance/docs for Jupyter installation here: https://github.com/rstudio/rstudio-pro/pull/5166
> Update jupyter install

- internal/jupyter/install.go
Closes https://github.com/sol-eng/wbi/issues/186
> Update workbench_jupyterlab version

- internal/languages/python.go
Closes https://github.com/sol-eng/wbi/issues/187
> Disable installing 3.12.0 due to JupyterLab WB incompatibility

- internal/quarto/install.go
- main.go
Creating this PR so that I can delete the c_lib branch because it included a PAT in the commit history. This PR is planned to provide the ability for wbi to be compiled into a c library for reference from Python or other languages.
> Allow wbi to be compiled into a c-library for external reference
